import { useIsAuthenticated, useMsal } from '@azure/msal-react';
import Breadcrumb from 'components/molecules/Breadcrumb';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import styles from '../../styles/Home.module.css';

const Home: NextPage = () => {
	const { instance } = useMsal();
	const isAuthenticated = useIsAuthenticated();

	useEffect(() => {
		if (!isAuthenticated && instance) {
			setTimeout(() => {
				instance.loginRedirect();
			}, 1000);
		}
	}, [instance]);

	return (
		<div className={styles.container}>
			<Head>
				<title>Portal</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Breadcrumb title={'Dashboard'} />
			<main className={styles.main}>
				<h1 className={styles.title}>Welcome to Portal</h1>
			</main>
		</div>
	);
};

export default Home;
